//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesData
    {
        public int Id { get; set; }
        public Nullable<int> Sales { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
        public string DateString { get; set; }
    }
}
